---
#- name: Configure Jenkins Slaves
#  hosts: slave_servers
#  become: yes
#  roles:
#          - slave

- name: Install & Configure Jenkins
  hosts: jenkins_servers
  become: yes
  roles:
          - jenkins

