---
- name: Configure Nexus server
  hosts: nexus_servers
  become: yes
  roles:
    - nexus-server-setup

- name: Install & Configure prod
  hosts: production_servers
  become: yes
  roles:
    - production-server-setup
