---
- name: Install and upgrade pip
  yum:
    name:
            - pip
            - python-pip
    state: present

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Allow access to insecure registry
  copy:
    content: "{\"insecure-registries\": [\"{{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}\"]}"
    dest: "/etc/docker/daemon.json"

- name: Restart systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Delete old docker.pid
  ansible.builtin.file:
    path: /var/run/docker.pid
    state: absent

- name: Start Docker socket
  service:
    name: docker.socket
    state: restarted
    enabled: yes

- name: Start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
