---

- name: Install and upgrade pip
  yum:
    name:
            - pip
            - python-pip
    state: present

- name: yum install docker
  yum:
    name: docker
    state: latest

- name: Aba
  pip:
          name:
                  - docker
                  - six
          state: present
          extra_args: --ignore-installed
  become_user: ec2-user

- name: Allow access to insecure registry
  copy:
    content: "{\"insecure-registries\": [\"{{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***\"]***REMOVED***"
    dest: "/etc/docker/daemon.json"

- name: systemd restart
  ansible.builtin.systemd:
    daemon_reload: yes

- name: kill all dockers
  shell: "echo 1"

- name: delete old docker.pid
  ansible.builtin.file:
    path: /var/run/docker.pid
    state: absent

- name: Start Docker socket
  service:
    name: docker.socket
    state: restarted
    enabled: yes

- name: Start Docker socket
  service:
    name: docker
    state: restarted
    enabled: yes

- name: docker login
  docker_login:
    registry: "{{ nexus_default_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***"
    username: admin
    password: "{{ nexus_admin_password ***REMOVED******REMOVED***"
  become_user: ec2-user
