---
# tasks file for nexus-server-setup
- name: docker login
  docker_login:
    registry: "{{ nexus_default_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***"
    username: admin
    password: "{{ nexus_admin_password ***REMOVED******REMOVED***"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop running containers
  docker_container:
    name: "{{ item ***REMOVED******REMOVED***"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list ***REMOVED******REMOVED***"

- name: pull latest
  docker_image:
    name: "{{ nexus_default_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
    source: pull
    state: present

- name: run docker
  community.docker.docker_container:
    state: started
    name: "{{ docker_default_image_name ***REMOVED******REMOVED***"
    image: "{{ nexus_default_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
    ports:
      - "8080:8080"
      - "8081:8081"
