---
# tasks file for nexus-server-setup
- name: docker login
  docker_login:
    registry: "{{ nexus_default_host }}:{{ nexus_docker_hosted_port }}"
    username: admin
    password: "{{ nexus_admin_password }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop running containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

- name: pull latest
  docker_image:
    name: "{{ nexus_default_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"
    source: pull
    state: present

- name: run docker
  community.docker.docker_container:
    state: started
    name: "{{ docker_default_image_name }}"
    image: "{{ nexus_default_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"
    ports:
      - "8080:8080"
      - "8081:8081"
