---
# tasks file for nexus-server-setup
#- name: docker login
#  docker_login:
#    registry: "{{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}"
#    username: admin
#    password: "{{ nexus_admin_password }}"
#  vars:
#    ansible_python_interpreter: /usr/bin/python3

- name: shell login
  shell: "docker login -u admin -p {{ nexus_admin_password }} {{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}"

#- name: Get running containers
#  docker_host_info:
#    containers: yes
#  register: docker_info

- name: shell stop all conatiners
  shell: "docker stop $(docker ps -a -q)"

#- name: Stop running containers
#  docker_container:
#    name: "{{ item }}"
#    state: stopped
#  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

#- name: pull latest
#  docker_image:
#    name: "{{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"
#    source: pull
#    state: present

- name: shell pull latest
  shell: "docker pull {{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"

#- name: run docker
#  community.docker.docker_container:
#    state: started
#    name: "{{ docker_default_image_name }}"
#    image: "{{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"
#    ports:
#      - "8080:8080"
#      - "8081:8081"

- name: shell run
  shell: "docker run -d --privileged=true -p 8080:8080 {{ hostvars.nexus_linux.ansible_host }}:{{ nexus_docker_hosted_port }}/{{ docker_default_image_name }}"
