---
# tasks file for nexus-server-setup
#- name: docker login
#  docker_login:
#    registry: "{{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***"
#    username: admin
#    password: "{{ nexus_admin_password ***REMOVED******REMOVED***"
#  vars:
#    ansible_python_interpreter: /usr/bin/python3

- name: shell login
  shell: "docker login -u admin -p {{ nexus_admin_password ***REMOVED******REMOVED*** {{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***"

#- name: Get running containers
#  docker_host_info:
#    containers: yes
#  register: docker_info

- name: shell stop all conatiners
  shell: "docker ps -a | wc -l"
  register: hjhjh


- name: shell stop all conatiners
  shell: "docker stop $(docker ps -a -q)"
  when: "{{ hjhjh.stdout ***REMOVED******REMOVED***" != 0

#- name: Stop running containers
#  docker_container:
#    name: "{{ item ***REMOVED******REMOVED***"
#    state: stopped
#  loop: "{{ docker_info.containers | map(attribute='Id') | list ***REMOVED******REMOVED***"

#- name: pull latest
#  docker_image:
#    name: "{{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
#    source: pull
#    state: present

- name: shell pull latest
  shell: "docker pull {{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
  register: h

- debug:
    msg: "{{ h ***REMOVED******REMOVED***"

#- name: run docker
#  community.docker.docker_container:
#    state: started
#    name: "{{ docker_default_image_name ***REMOVED******REMOVED***"
#    image: "{{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
#    ports:
#      - "8080:8080"
#      - "8081:8081"

- name: shell run
  shell: "docker run -d --privileged=true -p 8080:8080 {{ hostvars.nexus_linux.ansible_host ***REMOVED******REMOVED***:{{ nexus_docker_hosted_port ***REMOVED******REMOVED***/{{ docker_default_image_name ***REMOVED******REMOVED***"
  register: h

- debug:
    msg: "{{ h ***REMOVED******REMOVED***"
