---
# handlers file for jenkins
- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted
  listen: "Restart Jenkins"

- name: Wait until Jenkins is available
  uri:
    url: "{{ jenkins_url }}"
    url_username: "{{ jenkins_username }}"
    url_password: "{{ jenkins_password }}"
    validate_certs: False
    force_basic_auth: yes
  listen: "Wait Jenkins"
  register: result
  until: result.status == 200
  retries: 16
  delay: 5
