---
- name: Checking settings file
  stat:
    path: "{{ nexus_installation_dir ***REMOVED******REMOVED***/nexus/bin/nexus"
  register: stat_result

- name: Check that Nexus installation is correct
  debug:
    msg: Nexus is not installed
  when: not stat_result.stat.exists

- name: ERROR WILE INSTALLING NEXUS
  meta: end_play
  when: not stat_result.stat.exists

- name: Copying repositories settings
  copy:
    src: "rest_jsons"
    dest: "{{ nexus_installation_dir ***REMOVED******REMOVED***"
    owner: "{{ nexus_os_user ***REMOVED******REMOVED***"
    group: "{{ nexus_os_group ***REMOVED******REMOVED***"
    mode: 0644

- name: Waiting for opening HTTPS port
  wait_for:
    port: 8443
    delay: 10

- name: Checking if admin password file exists
  stat:
    path: "{{ nexus_download_dir ***REMOVED******REMOVED***/nexus/bin/nexus"
  register: adm_pass_exists

- name: Changing admin password
  shell: "curl -v -X PUT -u admin:\"$(cat {{ nexus_installation_dir ***REMOVED******REMOVED***/sonatype-work/nexus3/admin.password)\" --header \"Content-Type: text/plain\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/security/users/admin/change-password\" --data \"{{ nexus_admin_password ***REMOVED******REMOVED***\""
  register: result
  when: adm_pass_exists.stat.exists

- debug:
    var: result

- name: Create maven hosted snapshot repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_hosted_snapshot_repo.json"
  register: result

- debug:
    var: result

- name: Create maven hosted release repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_hosted_release_repo.json"
  register: result

- debug:
    var: result

- name: Create maven proxy repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/proxy\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_proxy_repo.json"
  register: result

- debug:
    var: result

- name: Adding Docker realm using REST API
  shell: "curl -v -X PUT -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/security/realms/active\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/realms.json"
  register: result

- debug:
    var: result

- name: Create docker hosted release repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_hosted_release_repo.json"
  register: result

- debug:
    var: result

- name: Create docker hosted snapshot repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_hosted_snapshot_repo.json"
  register: result

- debug:
    var: result

- name: Create docker proxy repository using REST API
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/proxy\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_proxy_repo.json"
  register: result

- debug:
    var: result
