---
- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart nexus
  ansible.builtin.systemd:
    name: nexus
    state: restarted

- name: Check settings
  stat:
    path: "{{ nexus_installation_dir ***REMOVED******REMOVED***/nexus/bin/nexus"
  register: stat_result

- name: check nexus is not installed
  debug:
    msg: Nexus is not installed
  when: not stat_result.stat.exists

- name: check nexus is not installed - exit
  meta: end_play
  when: not stat_result.stat.exists

- name: copying jsons
  copy:
    src: "rest_jsons"
    dest: "{{ nexus_installation_dir ***REMOVED******REMOVED***"
    owner: "{{ nexus_os_user ***REMOVED******REMOVED***"
    group: "{{ nexus_os_group ***REMOVED******REMOVED***"
    mode: 0644

- name: Wait for port 8081 (until nexus will start)
  wait_for:
    port: 8443
    delay: 10

- name: Check that the admin password file exists
  stat:
    path: "{{ nexus_download_dir ***REMOVED******REMOVED***/nexus/bin/nexus"
  register: adm_pass_exists

- name: REST edit admin password (if exists)
  shell: "curl -v -X PUT -u admin:\"$(cat {{ nexus_installation_dir ***REMOVED******REMOVED***/sonatype-work/nexus3/admin.password)\" --header \"Content-Type: text/plain\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/security/users/admin/change-password\" --data \"{{ nexus_admin_password ***REMOVED******REMOVED***\""
  register: result
  when: adm_pass_exists.stat.exists

- debug:
    var: result

- name: REST create maven hosted snapshot repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_hosted_snapshot_repo.json"
  register: result

- debug:
    var: result

- name: REST create maven hosted release repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_hosted_release_repo.json"
  register: result

- debug:
    var: result

- name: REST create maven proxy repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/maven/proxy\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/maven_proxy_repo.json"
  register: result

- debug:
    var: result

- name: REST add docker realm
  shell: "curl -v -X PUT -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/security/realms/active\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/realms.json"
  register: result

- debug:
    var: result

- name: REST create docker hosted release repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_hosted_release_repo.json"
  register: result

- debug:
    var: result

- name: REST create docker hosted snapshot repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/hosted\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_hosted_release_repo.json"
  register: result

- debug:
    var: result

- name: REST create docker proxy repo
  shell: "curl -v -X POST -u admin:{{ nexus_admin_password ***REMOVED******REMOVED*** -H \"accept: application/json\" --header \"Content-Type: application/json\" \"https://{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***:{{ nexus_https_port ***REMOVED******REMOVED***/service/rest/v1/repositories/docker/proxy\" -d @{{ nexus_installation_dir ***REMOVED******REMOVED***/rest_jsons/docker_proxy_repo.json"
  register: result

- debug:
    var: result
