---
- name: Upload plugins
  community.general.jenkins_plugin:
          name: '{{ item ***REMOVED******REMOVED***'
          state: present
          url_username: '{{ jenkins_username ***REMOVED******REMOVED***'
          url_password: '{{ jenkins_password ***REMOVED******REMOVED***'
          url: '{{ jenkins_url ***REMOVED******REMOVED***'
  with_items: '{{ jenkins_plugins ***REMOVED******REMOVED***'
  notify:
          - "Restart Jenkins"
          - "Wait Jenkins"

- name: Flush handlers
  meta: flush_handlers

- name: Generate an SSH keys for slaves
  community.crypto.openssh_keypair:
    path: /tmp/jenkins_slaves_ssh_rsa
  register: public_slaves_ssh

- name: Get private key for Jenkins slaves
  shell: cat /tmp/jenkins_slaves_ssh_rsa
  register: private_slaves_ssh

- name: Set private key for slaves
  set_fact:
          ssh_credentials: "{{ ssh_credentials | combine({'slaves_credentials': {'private_key': '{{ private_slaves_ssh.stdout ***REMOVED******REMOVED***'***REMOVED******REMOVED***, recursive=true) ***REMOVED******REMOVED***"

- name: Upload jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/jenkins_jobs/{{ item.value ***REMOVED******REMOVED***') ***REMOVED******REMOVED***"
    name: "{{ item.key ***REMOVED******REMOVED***" 
    password: "{{ jenkins_password ***REMOVED******REMOVED***"
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    user: "{{ jenkins_username ***REMOVED******REMOVED***"
  with_dict: {PreCommit: pre_commit_job.xml, Deployment: deployment_job.xml, Build: build_job.xml***REMOVED***

- name: Upload SSH credentials
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/credentials/secret_ssh.groovy") ***REMOVED******REMOVED***'
    args: "{{ item.value ***REMOVED******REMOVED***"
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ ssh_credentials ***REMOVED******REMOVED***"

- name: Upload username and password credentials
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/credentials/secret_password.groovy") ***REMOVED******REMOVED***'
    args: "{{ item.value ***REMOVED******REMOVED***"
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ password_credentials ***REMOVED******REMOVED***"

- name: Upload Slaves
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/slaves/slave.groovy") ***REMOVED******REMOVED***'
    args: '{{ item.value ***REMOVED******REMOVED***'
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ slaves ***REMOVED******REMOVED***"
