---
- name: Generate an SSH keys for slaves
  community.crypto.openssh_keypair:
    path: /tmp/jenkins_slaves_ssh_rsa
  register: public_slaves_ssh

- name: Debug
  debug:
          msg: "{{ public_slaves_ssh.public_key ***REMOVED******REMOVED***"

- name: Get private key for Jenkins slaves
  shell: cat /tmp/jenkins_slaves_ssh_rsa
  register: private_slaves_ssh

- name: Debug
  debug:
          msg: "{{ private_slaves_ssh.stdout ***REMOVED******REMOVED***"

- name: Upload plugins
  community.general.jenkins_plugin:
          name: '{{ item ***REMOVED******REMOVED***'
          state: present
          url_username: '{{ jenkins_username ***REMOVED******REMOVED***'
          url_password: '{{ jenkins_password ***REMOVED******REMOVED***'
          url: '{{ jenkins_url ***REMOVED******REMOVED***'
  with_items: '{{ jenkins_plugins ***REMOVED******REMOVED***'
  register: installed_plugins

- name: Jenkins restart fact after plugins installation
  ansible.builtin.set_fact:
          jenkins_restart_required: no

- name: Check if restart is required by any of the plugins
  ansible.builtin.set_fact:
          jenkins_restart_required: yes
  when: item.changed
  with_items: "{{ installed_plugins.results ***REMOVED******REMOVED***"

- name: Restart Jenkins
  ansible.builtin.service:
          name: jenkins
          state: restarted
  when: jenkins_restart_required
  notify: Wait until Jenkins is available

- name: Wait until Jenkins is available
  shell: curl -I -u '{{ jenkins_username ***REMOVED******REMOVED***':'{{ jenkins_password ***REMOVED******REMOVED***' '{{ jenkins_url ***REMOVED******REMOVED***'
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5
  changed_when: false
  args:
    warn: false

- name: Reset the fact after plugins installation to Jenkins
  ansible.builtin.set_fact:
          jenkins_restart_required: no
  when: jenkins_restart_required

- name: Plugin enabling
  community.general.jenkins_plugin:
          name: "{{ item ***REMOVED******REMOVED***"
          state: enabled
          url_username: '{{ jenkins_username ***REMOVED******REMOVED***'
          url_password: '{{ jenkins_password ***REMOVED******REMOVED***'
          url: '{{ jenkins_url ***REMOVED******REMOVED***'
  with_items: "{{ jenkins_plugins ***REMOVED******REMOVED***"

- name: Generate SSH
  shell: ssh-

- name: Upload jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/jenkins_jobs/{{ item.value ***REMOVED******REMOVED***') ***REMOVED******REMOVED***"
    name: "{{ item.key ***REMOVED******REMOVED***" 
    password: "{{ jenkins_password ***REMOVED******REMOVED***"
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    user: "{{ jenkins_username ***REMOVED******REMOVED***"
  with_dict: {PreCommit: pre_commit_job.xml, Deployment: deployment_job.xml, Build: build_job.xml***REMOVED***

- name: Upload SSH credentials
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/credentials/secret_ssh.groovy") ***REMOVED******REMOVED***'
    args: "{{ item.value ***REMOVED******REMOVED***"
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ ssh_credentials ***REMOVED******REMOVED***"

- name: Upload username and password credentials
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/credentials/secret_password.groovy") ***REMOVED******REMOVED***'
    args: "{{ item.value ***REMOVED******REMOVED***"
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ password_credentials ***REMOVED******REMOVED***"

- name: Upload Slaves
  jenkins_script:
    url: "{{ jenkins_url ***REMOVED******REMOVED***"
    script: '{{ lookup("template", "templates/jenkins_groovy/slaves/slave.groovy") ***REMOVED******REMOVED***'
    args: '{{ item.value ***REMOVED******REMOVED***'
    user: '{{ jenkins_username ***REMOVED******REMOVED***'
    password: '{{ jenkins_password ***REMOVED******REMOVED***'
    validate_certs: false
    timeout: "120"
  with_dict: "{{ slaves ***REMOVED******REMOVED***"
