---
- name: Create jenkins user
  user:
    name: jenkins
    comment: "Jenkins slave user"
    home: "{{ jenkins_home }}"
    shell: /bin/bash

- name: Create .ssh folder
  file:
    path: "{{ jenkins_home }}/.ssh"
    state: directory
    mode: 0700
    owner: jenkins

- name: Add passwordless connection for Jenkins
  authorized_key:
    user: jenkins
    key: "{{ pulbic_key }}"

- name: Update authorized keys rights
  file:
    path: "{{ jenkins_home }}/.ssh/authorized_keys"
    state: file
    mode: 0600
    owner: jenkins

- name: Install recommended packages
  yum:
    name:
      - maven
      - java-1.8.0-openjdk
      - git
      - docker

- name: Check if swap file exists
  stat:
    path: swapfile
  register: swap_file_check

- name: Create swap file
  command: "dd if=/dev/zero of=swapfile bs=1M count={{ swap_file_size_gb }}K"
  when: not swap_file_check.stat.exists

- name: Change swap file permissions
  file:
    path: swapfile
    owner: root
    group: root
    mode: 0600
  when: not swap_file_check.stat.exists

- name: Make swap file
  command: mkswap swapfile
  when: not swap_file_check.stat.exists

- name: Mount swap file
  command: swapon swapfile
  when: not swap_file_check.stat.exists

- name: Create .m2 folder
  file:
    path: "{{ jenkins_home }}/.m2"
    state: directory
    owner: jenkins

- name: Copy maven configuration
  template:
    src: templates/settings.xml
    dest: "{{ jenkins_home }}/.m2/"

- name: Add Jenkins to Docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Docker socket
  systemd:
    name: docker.socket
    state: restarted

- name: create ssl dir
  file:
      path: "/etc/ssl"
      state: "directory"
      owner: "jenkins"
      group: "jenkins"

- name: copy ssls
  copy:
      src: "~/Documents/NexusSSL.pem"
      dest: "/etc/ssl"

- name: trust cert
  shell: "update-ca-trust force-enable"

- name: copy cert
  copy:
      src: "/etc/ssl/NexusSSL.pem"
      dest: "/etc/pki/ca-trust/source/anchors/"
      remote_src: yes

- name: trust cert
  shell: "update-ca-trust extract"

- name: create docker directory with certs
  file:
      path: "/etc/docker/certs.d/{{ hostvars.nexus_linux.ansible_host_dns }}:8444"
      state: directory
      owner: "jenkins"
      group: "jenkins"

- name: copy cert to docker
  copy:
      src: "/etc/ssl/NexusSSL.pem"
      dest: "/etc/docker/certs.d/{{ hostvars.nexus_linux.ansible_host_dns }}:8444/"
      remote_src: yes

- name: Start Docker
  systemd:
    name: docker
    state: restarted
    enabled: true
