---

- name: Create jenkins user
  user:
          name: jenkins
          comment: "Jenkins slave user"
          home: "{{ jenkins_home ***REMOVED******REMOVED***" 
          shell: /bin/bash

- name: Create .ssh folder
  file:
          path: "{{ jenkins_home ***REMOVED******REMOVED***/.ssh" 
          state: directory
          mode: 0700
          owner: jenkins

- name: Add passwordless connection for Jenkins
  authorized_key:
          user: jenkins
          key: "{{ pulbic_key ***REMOVED******REMOVED***"

- name: Update authorized_keys rights
  file:
          path: "{{ jenkins_home ***REMOVED******REMOVED***/.ssh/authorized_keys"
          state: file
          mode: 0600
          owner: jenkins

- name: Install recommended packages
  yum:
          name:
                  - maven
                  - java-1.8.0-openjdk
                  - git
                  - docker

- name: Create .m2 folder
  file:
          path: "{{ jenkins_home ***REMOVED******REMOVED***/.m2"
          state: directory
          owner: jenkins
 
- name: Copy maven configuration
  template:
          src: templates/settings.xml
          dest: "{{ jenkins_home ***REMOVED******REMOVED***/.m2/"

- name: Start Docker
  systemd:
          name: docker
          state: started
          enabled: true

- name: Open secured port 8085
  copy:
          content: |
               {  
                  "insecure-registries": ["{{ nexus_host ***REMOVED******REMOVED***:{{ nexus_port ***REMOVED******REMOVED***"]
               ***REMOVED***
          dest: /etc/docker/daemon.json


- name: Restart Docker
  systemd:
          name: docker
          state: restarted

- name: Restart Docker socket
  systemd:
          name: docker.socket
          state: restarted

- name: Give needed permissions to docker.sock
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '777'
