{% if item.registry is defined %***REMOVED***
FROM {{ item.registry.url ***REMOVED******REMOVED***/{{ item.image ***REMOVED******REMOVED***
{% else %***REMOVED***
FROM {{ item.image ***REMOVED******REMOVED***
{% endif %***REMOVED***

{% if item.env is defined %***REMOVED***
{% for var, value in item.env.items() %***REMOVED***
{% if value %***REMOVED***
ENV {{ var ***REMOVED******REMOVED*** {{ value ***REMOVED******REMOVED***
{% endif %***REMOVED***
{% endfor %***REMOVED***
{% endif %***REMOVED***

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v yum) ]; then yum makecache && yum install -y **systemd** python39 python3-pip sudo bash iproute firewalld policycoreutils-python-utils selinux-policy-devel selinux-policy-targeted policycoreutils setroubleshoot setroubleshoot-server && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates iproute2 && xbps-remove -O; fi

