---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
        - name: instance
          image: alekseychudov/centos8-systemd
          command: /sbin/init
          privileged: True
provisioner:
  name: ansible
  #linter: |
        #        ansible-linter
verifier:
  name: ansible
