---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: centos:8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    network_mode: host
    port_bindings:
      8080: 8080
      22: 22

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          jenkins_servers:
            hosts:
              jenkins_linux:
                ansible_host: localhost
                ansible_connection: local
          slave_servers:
            hosts:
              slave_linux:
                ansible_host: 0.0.0.0

verifier:
  name: ansible
