---
nexus_download_dir: "/app"
nexus_download_url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"

nexus_admin_password: "112263"
nexus_domain_name: "ec2-3-14-130-0.us-east-2.compute.amazonaws.com"
nexus_public_ip: ""
nexus_ssl_name: "NexusSSL"

nexus_repos_maven_proxy:
  - name: petclinic-maven-proxy
    remote_url: "https://repo1.maven.org/maven2/"
    layout_policy: permissive

nexus_repos_maven_hosted:
  - name: petclinic-maven-hosted
    version_policy: mixed
    layout_policy: permissive
    deployment_policy: allow-redeploy

nexus_repos_docker_hosted:
  - name: petclinic-docker-hosted
    http_port: "{{ nexus_docker_hosted_port }}"
    v1_enabled: True
