---
nexus_download_dir: "/app"
nexus_download_url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"

nexus_admin_password: "112263"
nexus_domain_name: "{{ hostvars.nexus_linux.ansible_host_dns ***REMOVED******REMOVED***"
nexus_private_ip: "{{ hostvars.nexus_linux.ansible_host_private_ip ***REMOVED******REMOVED***"
nexus_ssl_name: "NexusSSL"
